### PR TITLE
Fixes and updates

### LINKED ISSUE #1102: Schedule in einem Skript kann nicht gestoppt werden bei Skript Stop
Script lässt sich nicht stoppen.

hier wurde das Script gestoppt und wieder gestartet. Da gibt es schon die 1. Error-Meldung.
```
javascript.0 2022-08-18 17:36:47.136	info	Start javascript script.js.Wetter.Wetter_to_FTP
javascript.0 2022-08-18 17:36:44.540	error	Error by canceling scheduled job "<Anonymous Job 23 2022-08-18T12:57:51.743Z>"
javascript.0 2022-08-18 17:36:44.539	info	Stop script script.js.Wetter.Wetter_to_FTP
```

Und hier dann doppelt im JS und Puppeteer
```
javascript.0 2022-08-18 17:39:03.369	error	script.js.Wetter.Wetter_to_FTP: Error on upload: Error: Command failed: wput -nc /opt/iobroker/iobroker-data/files/0_userdata.0/wetterstation.png ftp://xxxxx:xxxxx@www37.world4you.com ()
javascript.0 2022-08-18 17:39:03.184	error	script.js.Wetter.Wetter_to_FTP: Error on upload: Error: Command failed: wput -nc /opt/iobroker/iobroker-data/files/0_userdata.0/wetterstation.png ftp://xxxxx:xxxxx@www37.world4you.com ()
javascript.0 2022-08-18 17:39:03.157	info	script.js.Wetter.Wetter_to_FTP: exec: wput -nc /opt/iobroker/iobroker-data/files/0_userdata.0/wetterstation.png ftp://xxxxx:xxxxx@www37.world4you.com
puppeteer.0  2022-08-18 17:39:03.056	debug	Write file to "wetterstation.png"
javascript.0 2022-08-18 17:39:02.884	info	script.js.Wetter.Wetter_to_FTP: exec: wput -nc /opt/iobroker/iobroker-data/files/0_userdata.0/wetterstation.png ftp://xxxxx:xxxxx@www37.world4you.com
puppeteer.0  2022-08-18 17:39:02.783	debug	Write file to "wetterstation.png"
puppeteer.0  2022-08-18 17:39:00.289	debug	Message: {"command":"screenshot","message":{"url":"http://10.0.1.203:3000/d/sRh7W1m4k/wetterstation-copy-2?orgId=1&kiosk","clip":{"x":0,"y":0,"width":1000,"height":1100},"ioBrokerOptions":{"storagePath":"wetterstation.png"},"viewportOptions":{"width":1600,"height":1000}},"from":"system.adapter.javascript.0","callback":{"message":{"url":"http://10.0.1.203:3000/d/sRh7W1m4k/wetterstation-copy-2?orgId=1&kiosk","clip":{"x":0,"y":0,"width":1000,"height":1100},"ioBrokerOptions":{"storagePath":"wetterstation.png"},"viewportOptions":{"width":1600,"height":1000}},"id":298,"ack":false,"time":1660837140274},"_id":79533595}
puppeteer.0  2022-08-18 17:39:00.289	debug	Message: {"command":"screenshot","message":{"url":"http://10.0.1.203:3000/d/sRh7W1m4k/wetterstation-copy-2?orgId=1&kiosk","clip":{"x":0,"y":0,"width":1000,"height":1100},"ioBrokerOptions":{"storagePath":"wetterstation.png"},"viewportOptions":{"width":1600,"height":1000}},"from":"system.adapter.javascript.0","callback":{"message":{"url":"http://10.0.1.203:3000/d/sRh7W1m4k/wetterstation-copy-2?orgId=1&kiosk","clip":{"x":0,"y":0,"width":1000,"height":1100},"ioBrokerOptions":{"storagePath":"wetterstation.png"},"viewportOptions":{"width":1600,"height":1000}},"id":297,"ack":false,"time":1660837140273},"_id":79533594}
```

JS-Adapter: 6.0.0
Node.js: 16.15.1
NPM: 8.11.0
JS-Controller: 4.0.23

### LINKED ISSUE #1131: setSTateDelayed for selector
Is it possible to implement additional to

`$('channel[role=switch](rooms=Living room)[state.id=*.STATE]').setState(false)`

some funktion like this:

`$('channel[role=switch](rooms=Living room)[state.id=*.STATE]').setStateDelayed(false,1000)`

### LINKED ISSUE #1152: "echo" in exec() doesn't execute /bin/echo, but echo command of /bin/sh - confusing
### Test 1

When running ``echo -n -e "\x41"`` with bash, everything works like expected. Output is ``A``.

But if I use this script in JavaScript adapter (on the same system):

```javascript
exec(`echo -n -e "\\x41"`, async function (error, result, stderr) {
    console.log(result);
});
```

Output is ``-e \x41``

Why is the option -e added to the output and is not interpreted?!

----

### Test 2

When running ``/bin/echo -n -e "\x41"`` with bash, everything works like expected. Output is ``A``.

With this script in JavaScript adapter (on the same system):

```javascript
exec(`/bin/echo -n -e "\\x41"`, async function (error, result, stderr) {
    console.log(result);
});
```

The output is also ``A``. Whats the difference to Test 1? (``which echo`` returns ``/bin/echo`` in all cases)

----

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: 4.0.23
 - Node version: v16.17.0
 - Operating system: Debian Bullseye

**See:**

- https://nodejs.org/docs/latest-v16.x/api/child_process.html#child_processexeccommand-options-callback
- https://linux.die.net/man/1/echo

```
-n
    do not output the trailing newline
-e
    enable interpretation of backslash escapes
```

### LINKED ISSUE #1167: make configurable max io for adapter
i need a message or restart or anything when adapter has io > 3000 (maybe configurable in admin like threshold value )
grafik

### PR DESCRIPTION
**Pull request by Apollon77**
* (Apollon77) Add a configurable check for number of setStates per Minute to prevent scripts from taking down ioBroker. Default are 1000 setState per minute. Only stops if the number is reached 2 minutes in a row! (fixes #1167)
* (Apollon77) Add createAlias method to create aliases for states (foxes #966)
* (Apollon77) Add setStateDelayed to selector (fixes #1131)
* (Apollon77) Add options to exec command (fixes #1152)
* (Apollon77) Fix issues with cancelling schedules when stopping scripts, fixes #1102
* update deps

### CODE REVIEW

File: main.js [hunk 1]
```diff
@@ -1176,6 +1179,25 @@ function main() {
...
 
+                // CHeck setState counter per minute and stop script if too high
+                setStateCountCheckInterval = setInterval(() => {
+                    Object.keys(context.scripts).forEach(id => {
+                        const currentSetStatePerMinuteCounter = context.scripts[id].setStatePerMinuteCounter;
+                        context.scripts[id].setStatePerMinuteCounter = 0;
+                        if (currentSetStatePerMinuteCounter > adapter.config.maxSetStatePerMinute) {
+                            context.scripts[id].setStatePerMinuteProblemCounter++;
+                            adapter.log.debug(`Script ${id} has reached the maximum of ${adapter.config.maxSetStatePerMinute} setState calls per minute in ${context.scripts[id].setStatePerMinuteProblemCounter} consecutive minutes`);
+                            if (context.scripts[id].setStatePerMinuteProblemCounter > 1) {
```
Comment (foxriver76) [inline main.js:1190]: maybe put the threshold in a constant, this would be more self explanatory and less magic numbers +  a central place to change the threshold

File: main.js [hunk 2]
```diff
@@ -1693,6 +1715,8 @@ function execute(script, name, verbose, debug) {
     script._id = Math.floor(Math.random() * 0xFFFFFFFF);
     script.subscribes = {};
     script.subscribesFile = {};
+    script.setStatePerMinuteCounter = 0;
```
Comment (foxriver76) [inline main.js:1718]: where is this counter increased? maybe I am just blind

File: lib/javascript.d.ts [hunk 3]
```diff
@@ -1265,7 +1268,7 @@ declare global {
 	/**
 	 * Executes a system command
 	 */
-	function exec(command: string, callback?: (err: Error | null | undefined, stdout: string, stderr: string) => void | Promise<void>): child_process.ChildProcess;
+	function exec(command: string, options?: Record<string, unknown>, callback?: (err: Error | null | undefined, stdout: string, stderr: string) => void | Promise<void>): child_process.ChildProcess;
```
Comment (foxriver76) [inline lib/javascript.d.ts:1271]: now it will not recognize the cb function if just two arguments passed. So either an overload or maybe we can just reexport the `child_process.exec` function completely, this will also give syntax completion and checking for the options parameter.

**Review by foxriver76 — CHANGES_REQUESTED** [review]
basically lgtm, my biggest concern is that I don't see the counter being increased. So lets clarify this first.

File: main.js (hunk 1 above)
Comment (Apollon77) [reply main.js:1190]: Because of the fact that this "2 mins in a row" thing is basically "prevent a script from being killed directly on start or such but allowing one minute" I would add kroe a comment. but I think it makes no sense to ever adjust that to a higher value

File: main.js (hunk 2 above)
Comment (Apollon77) [reply main.js:1718]: sandbox.js -> https://github.com/ioBroker/ioBroker.javascript/pull/1170/files#diff-e3370b4f11191861935af54f280f4be0f3e7e279c042c9a4a8db1cec0cf29393R442

File: lib/javascript.d.ts (hunk 3 above)
Comment (Apollon77) [reply lib/javascript.d.ts:1271]: How do I need todo it for the re-export?
