### PR TITLE
diverse mirror fixes

### LINKED ISSUE #551: Ständiger Neustart durch Mirroring-Funktion
Hab mein System von JSC 3.0.20 / JSE 4.5.1 auf den JSC 3.1.3 upgrade wollen.
(hier der Link zur Diskussion im Forum --> https://forum.iobroker.net/topic/32481/js-controller-3-0-3-1-jetzt-im-latest/882
Ergebnis, der Controller ist in einer Restart-Schleife. Downgrade des JSC auf 3.0.20 ohne Erfolg. Restore eines Backups (mit vorher laufendem JSC 3.0.20) ohne Erfolg.
Lösung war dann, das deaktivieren des Mirrorings im JSE-Adapter.
Das Mirroring hatte ich vor ca. 2 Wochen aktiviert und es hatte ohne Probleme funktioniert.
Hier ein Log-Auszug vom Fehler
```

2020-05-10 11:35:32.142  - [32minfo[39m: host.Smarthome "system.adapter.javascript.0" enabled
--
  | 2020-05-10 11:35:32.174  - [32minfo[39m: host.Smarthome instance system.adapter.javascript.0 started with pid 20479
  | 2020-05-10 11:35:33.677  - [32minfo[39m: javascript.0 (20479) starting. Version 4.5.1 in /opt/iobroker/node_modules/iobroker.javascript, node: v12.16.3, js-controller: 3.0.20
  | 2020-05-10 11:35:33.729  - [32minfo[39m: javascript.0 (20479) requesting all states
  | 2020-05-10 11:35:33.730  - [32minfo[39m: javascript.0 (20479) requesting all objects
  | 2020-05-10 11:35:34.699  - [32minfo[39m: javascript.0 (20479) received all objects
  | 2020-05-10 11:35:34.833  - [32minfo[39m: javascript.0 (20479) received all states
  | 2020-05-10 11:35:35.481  - [31merror[39m: javascript.0 (20479) uncaught exception: Cannot read property 'ts' of undefined
  | 2020-05-10 11:35:35.482  - [31merror[39m: javascript.0 (20479) TypeError: Cannot read property 'ts' of undefined
  | at Mirror.sync (/opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:214:92)
  | at Mirror.sync (/opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:207:22)
  | at /opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:49:22
  | at /opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:553:23
  | at _0x30230c._applyViewFunc (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:116731)
  | at processTicksAndRejections (internal/process/task_queues.js:97:5)
  | 2020-05-10 11:35:35.494  - [32minfo[39m: javascript.0 (20479) terminating
  | 2020-05-10 11:35:35.495  - [32minfo[39m: javascript.0 (20479) Terminated (NO_ERROR): Without reason
  | 2020-05-10 11:35:36.022  - [31merror[39m: host.Smarthome Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
  | 2020-05-10 11:35:36.023  - [31merror[39m: host.Smarthome Caught by controller[1]: TypeError: Cannot read property 'ts' of undefined
  | 2020-05-10 11:35:36.023  - [31merror[39m: host.Smarthome Caught by controller[1]:     at Mirror.sync (/opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:214:92)
  | 2020-05-10 11:35:36.023  - [31merror[39m: host.Smarthome Caught by controller[1]:     at Mirror.sync (/opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:207:22)
  | 2020-05-10 11:35:36.024  - [31merror[39m: host.Smarthome Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:49:22
  | 2020-05-10 11:35:36.024  - [31merror[39m: host.Smarthome Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:553:23
  | 2020-05-10 11:35:36.024  - [31merror[39m: host.Smarthome Caught by controller[1]:     at _0x30230c._applyViewFunc (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:116731)
  | 2020-05-10 11:35:36.024  - [31merror[39m: host.Smarthome Caught by controller[1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
  | 2020-05-10 11:35:36.025  - [32minfo[39m: host.Smarthome instance system.adapter.javascript.0 terminated with code 0 (NO_ERROR)
  | 2020-05-10 11:35:36.025  - [32minfo[39m: host.Smarthome Restart adapter system.adapter.javascript.0 because enabled
  | 2020-05-10 11:36:06.053  - [32minfo[39m: host.Smarthome instance system.adapter.javascript.0 started with pid 20503
  | 2020-05-10 11:36:07.714  - [32minfo[39m: javascript.0 (20503) starting. Version 4.5.1 in /opt/iobroker/node_modules/iobroker.javascript, node: v12.16.3, js-controller: 3.0.20
  | 2020-05-10 11:36:07.766  - [32minfo[39m: javascript.0 (20503) requesting all states
  | 2020-05-10 11:36:07.767  - [32minfo[39m: javascript.0 (20503) requesting all objects
  | 2020-05-10 11:36:08.683  - [32minfo[39m: javascript.0 (20503) received all objects
  | 2020-05-10 11:36:08.824  - [32minfo[39m: javascript.0 (20503) received all states
  | 2020-05-10 11:36:09.468  - [31merror[39m: javascript.0 (20503) uncaught exception: Cannot read property 'ts' of undefined
  | 2020-05-10 11:36:09.469  - [31merror[39m: javascript.0 (20503) TypeError: Cannot read property 'ts' of undefined
  | at Mirror.sync (/opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:214:92)
  | at Mirror.sync (/opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:207:22)
  | at /opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:49:22
  | at /opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:553:23
  | at _0x30230c._applyViewFunc (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:116731)
  | at processTicksAndRejections (internal/process/task_queues.js:97:5)
  | 2020-05-10 11:36:09.477  - [32minfo[39m: javascript.0 (20503) terminating
  | 2020-05-10 11:36:09.477  - [32minfo[39m: javascript.0 (20503) Terminated (NO_ERROR): Without reason
  | 2020-05-10 11:36:10.010  - [31merror[39m: host.Smarthome Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
  | 2020-05-10 11:36:10.011  - [31merror[39m: host.Smarthome Caught by controller[1]: TypeError: Cannot read property 'ts' of undefined
  | 2020-05-10 11:36:10.011  - [31merror[39m: host.Smarthome Caught by controller[1]:     at Mirror.sync (/opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:214:92)
  | 2020-05-10 11:36:10.011  - [31merror[39m: host.Smarthome Caught by controller[1]:     at Mirror.sync (/opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:207:22)
  | 2020-05-10 11:36:10.012  - [31merror[39m: host.Smarthome Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:49:22
  | 2020-05-10 11:36:10.012  - [31merror[39m: host.Smarthome Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:553:23
  | 2020-05-10 11:36:10.012  - [31merror[39m: host.Smarthome Caught by controller[1]:     at _0x30230c._applyViewFunc (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:116731)
  | 2020-05-10 11:36:10.012  - [31merror[39m: host.Smarthome Caught by controller[1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
  | 2020-05-10 11:36:10.013  - [32minfo[39m: host.Smarthome instance system.adapter.javascript.0 terminated with code 0 (NO_ERROR)
  | 2020-05-10 11:36:10.013  - [32minfo[39m: host.Smarthome Restart adapter system.adapter.javascript.0 because enabled
  | 2020-05-10 11:36:14.480  - [32minfo[39m: host.Smarthome "system.adapter.javascript.0" disabled

```
Wenn noch Bedarf an Log-Informationen besteht kurz melden.
Gruß Steffen

### PR DESCRIPTION
**Pull request by Garfonso**
This is an extended version of #550 - like #550 this should also fix #551 
I did some more fixes and cleanup in mirror.js. Those are not as critical and are not really complete, yet, but I lost time to finish them. So maybe it is a good idea to merge them and let me find time to continue improvements later (or somebody else).
Things changed / fixed:
- catch write errors
- fix crash on start in line 214 with .ts of undefined because of trailing slash in config and bogus ids for diskList
- fix some errors / oversights with disk-ids in sync 
- fixed typo in some Regex which also caused disk-ids to go bogus
- replaced deprecated use of new Buffer
- rewrote createRecursiveDir to use node.js functionality (as per TODO comment)

Todo List:
- catch all read errors
- investigate possible issues and implement mirroring on multiple instances (at least on different hosts), probably including test cases.

### CODE REVIEW

**Comment by AlCalzone** [comment]
So, this fixes #551? If so, add "fixes #551" to the OP please :)

File: lib/mirror.js [hunk 1]
```diff
@@ -480,8 +496,8 @@ class Mirror {
                     folderDirParts.pop();
                     Mirror.createRecursiveDir(folderDirParts.join('/'));
```
Comment (AlCalzone) [inline lib/mirror.js:497]: If createRecursiveDir fails, should we even continue here?

Comment (Garfonso) [reply lib/mirror.js:497]: We probably should not. Not sure how to best change the situation.

Comment (Garfonso) [reply lib/mirror.js]: Ok, had an idea... hope you like it, see e7412ba.
